# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: David Koller
email: kolldavi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is David Koller I love technology and creating computer programs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dkoller.com" # the base hostname & protocol for your site
twitter_username: D_koller
github_username:  kolldavi

# Build settings
markdown: kramdown
